package com.conveyal.taui.models;

import com.conveyal.r5.analyst.scenario.StopSpec;
import com.conveyal.r5.util.ExceptionUtils;
import com.conveyal.taui.AnalysisServerException;
import com.vividsolutions.jts.geom.Coordinate;
import org.geotools.geometry.jts.JTS;
import org.geotools.referencing.crs.DefaultGeographicCRS;
import org.opengis.referencing.crs.CoordinateReferenceSystem;
import org.opengis.referencing.operation.TransformException;

import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import java.util.stream.Collectors;

/**
 * An intermediate step between the front-end representation of new or extended trips and the form that R5 expects.
 * Ideally we'd just convert directly to those R5 StopSpecs, but we need to use this intermediate type to track
 * distanceFromStart for generating hop times from speeds.
 * See conveyal/analysis-backend#175 for a potential cleaner solution.
 */
class ModificationStop {
    // General Constants
    private static double MIN_SPACING_PERCENTAGE = 0.25;
    private static int DEFAULT_SEGMENT_SPEED_KPH = 15;

    // Conversion Factors
    public static int SECONDS_PER_HOUR = 60 * 60;
    public static int METERS_PER_KM = 1000;

    /** The WGS84 latitude and longitude of the stop. */
    private final Coordinate coordinate;

    /** The GTFS stop_id of a stop if it's being reused, or null if it was newly created in the editor. */
    private final String id;

    /** True if the stop was one of the ones generated automatically at regular intervals along the new route. */
    private final boolean autoGenerated;

    private final double metersFromStart;
    private final int hopTime;

    /**
     * Constructor for ModificationStops. It creates an immutable object with all fields final.
     */
    private ModificationStop (Coordinate c, String id, boolean autoGenerated, double metersFromStart, int hopTime) {
        this.coordinate = c;
        this.id = id;
        this.autoGenerated = autoGenerated;
        this.metersFromStart = metersFromStart;
        this.hopTime = hopTime;
    }

    /**
     * Convert a list of ModificationStops (which are internal to the backend conversion process) to a list of the
     * StopSpec type required by r5.
     */
    static List<StopSpec> toStopSpecs (List<ModificationStop> stops) {
        return stops.stream()
                .map(s -> {
                    if (s.id == null || s.autoGenerated){
                        return new StopSpec(s.coordinate.x, s.coordinate.y);
                    } else {
                        // Stop references an existing GTFS stop ID, send that instead of its coordinates.
                        return new StopSpec(s.id);
                    }
                })
                .collect(Collectors.toList());
    }

    /**
     * Convert a list of Segments from a modification (the front-end representation) to this internal
     * backend representation.
     */
    static List<ModificationStop> getStopsFromSegments (List<Segment> segments, int[] segmentSpeedsKph) {
        // Keep a stack of Stops because as part of auto-generating stops we sometimes need to back one out.
        Stack<ModificationStop> stops = new Stack<>();
        CoordinateReferenceSystem crs = DefaultGeographicCRS.WGS84;

        if (segments == null || segments.size() == 0) {
            return new ArrayList<>();
        }

        Segment firstSegment = segments.get(0);

        if (firstSegment.stopAtStart) {
            stops.add(new ModificationStop(firstSegment.geometry.getCoordinates()[0],
                    firstSegment.fromStopId, false, 0, 0));
        }

        double metersToLastStop = 0; // distance to previously created stop, from start of pattern
        double metersFromPatternStart = 0; // from start of pattern
        int hopTime = 0;
        for (int i = 0; i < segments.size(); i++) {
            Segment segment = segments.get(i);
            int segmentSpeedKph = i < segmentSpeedsKph.length ? segmentSpeedsKph[i] : DEFAULT_SEGMENT_SPEED_KPH;
            double segmentSpeedMps = segmentSpeedKph * METERS_PER_KM / SECONDS_PER_HOUR;

            int stopSpacing = segment.spacing;
            boolean autoCreateStops = stopSpacing > 0;

            // TODO sanity check that each segment's final point matches the first point of the next segment
            Coordinate[] coords = segment.geometry.getCoordinates();
            for (int j = 1; j < coords.length; j++) {
                Coordinate c0 = coords[j - 1];
                Coordinate c1 = coords[j];
                double lineSegmentMeters;
                try {
                    // JTS orthodromic distance returns meters, considering the input coordinate system.
                    lineSegmentMeters = JTS.orthodromicDistance(c0, c1, crs);
                } catch (TransformException e) {
                    throw AnalysisServerException.unknown(ExceptionUtils.asString(e));
                }
                double metersAtEndOfSegment = metersFromPatternStart + lineSegmentMeters;

                if (autoCreateStops) {
                    // Auto-create stops while this segment includes at least one point that is more than 'spacing'
                    // meters farther along the pattern than the previously created stop.
                    while (metersToLastStop + stopSpacing < metersAtEndOfSegment) {
                        double frac = (metersToLastStop + stopSpacing - metersFromPatternStart)
                                / lineSegmentMeters;
                        if (frac < 0) {
                            frac = 0;
                        }
                        Coordinate c = new Coordinate(c0.x + (c1.x - c0.x) * frac, c0.y + (c1.y - c0.y) * frac);

                        // We can't just add segment.spacing because of converting negative fractions to zero above.
                        // This can happen when the last segment did not have automatic stop creation, or had a larger
                        // spacing. TODO in the latter case, we probably want to continue to apply the spacing from the
                        // last line segment until we create a new stop?
                        double metersToAutoCreatedStop = metersFromPatternStart + frac * lineSegmentMeters;

                        // Add the hop time
                        if (metersFromPatternStart > metersToLastStop) {
                            hopTime += (int) ((metersToAutoCreatedStop - metersFromPatternStart) / segmentSpeedMps);
                        } else {
                            hopTime += (int) ((metersToAutoCreatedStop - metersToLastStop) / segmentSpeedMps);
                        }

                        // Add the auto-created stop to the stack, flagging it as an auto-created one.
                        stops.add(new ModificationStop(c, null, true, metersToAutoCreatedStop, hopTime));

                        // Set the distance to the last stop
                        metersToLastStop = metersToAutoCreatedStop;

                        // Reset the hop time
                        hopTime = 0;
                    }
                }

                // Add the hop time for the rest of the segment or the entire segment if no auto-created stops were added.
                if (metersFromPatternStart > metersToLastStop) {
                    hopTime += (int) (lineSegmentMeters / segmentSpeedMps);
                } else {
                    hopTime += (int) ((metersAtEndOfSegment - metersToLastStop) / segmentSpeedMps);
                }

                metersFromPatternStart = metersAtEndOfSegment;
            }

            if (segment.stopAtEnd) {
                // If the last auto-generated stop was too close to a manually created stop (other than the first stop),
                // remove it.
                if (autoCreateStops && stops.size() > 1) {
                    ModificationStop lastStop = stops.peek();
                    double spacingPercentage = (metersFromPatternStart - metersToLastStop) / stopSpacing;
                    if (lastStop.autoGenerated && spacingPercentage < MIN_SPACING_PERCENTAGE) {
                        // Remove the stop and reset the distance to the last stop
                        stops.pop();
                        hopTime += lastStop.hopTime;
                    }
                }

                Coordinate endCoord = coords[coords.length - 1];
                stops.add(new ModificationStop(endCoord, segment.toStopId, false, metersFromPatternStart, hopTime));

                // Set the distance to the last stop
                metersToLastStop = metersFromPatternStart;

                // Reset the hop time
                hopTime = 0;
            }
        }

        return new ArrayList<>(stops);
    }

    static int[] getDwellTimes (List<ModificationStop> stops, Integer[] dwellTimes, int defaultDwellTime) {
        if (stops == null || stops.size() == 0) {
            return new int[0];
        }

        int[] stopDwellTimes = new int[stops.size()];

        // This "real" stop index is the index into the originally supplied stops, ignoring the auto-generated ones.
        int realStopIndex = 0;
        for (int i = 0; i < stops.size(); i++) {
            if (stops.get(i).autoGenerated || dwellTimes == null || dwellTimes.length <= realStopIndex) {
                stopDwellTimes[i] = defaultDwellTime;
            } else {
                Integer specificDwellTime = dwellTimes[realStopIndex];
                stopDwellTimes[i] = specificDwellTime != null ? specificDwellTime : defaultDwellTime;
                realStopIndex++;
            }
        }

        return stopDwellTimes;
    }

    static int[] getHopTimes (List<ModificationStop> stops) {
        if (stops == null || stops.size() < 2) {
            return new int[0];
        }

        // First stop has no hop.
        int[] hopTimes = new int[stops.size() - 1];
        for (int i = 1; i < stops.size(); i++) hopTimes[i - 1] = stops.get(i).hopTime;

        return hopTimes;
    }

}
