name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    # Start a separate docker container that we can contact over TCP (for tests)
    # Apparently there's something tricky going on with the port binding though
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idservices
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    # You can specify a docker container on which to run steps, rather than on the metal of runs-on above.
    # container:
    #   image: mherwig/docker-alpine-java-mongo:latest
    #   env:
    #     BUILD_TARGET:staging
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
      GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    # Java setup step completes very fast, no need to run in a preconfigured docker container
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.gradle/caches
        key: gradle-caches
    - name: Build and Publish with Gradle
      run: gradle publish
    # Use always switch on git describe to mimic behavior of Maven git ID plugin, to get same file name.
#    - name: Upload to S3
#      run: |
#        GIT_DESCRIBE=$(git describe --always)
#        aws s3 cp --no-progress --region eu-west-1 ./target/shaded/$GIT_DESCRIBE-cluster.jar s3://analysis-backend-builds
#        aws s3 cp --no-progress --region eu-west-1 ./target/shaded/$GIT_DESCRIBE.jar s3://r5-builds
#    # If this run is for the head of a branch, upload under the name branch-latest.jar
#    - name: Upload as branch-latest.jar
#      if: startsWith(github.ref, 'refs/heads/')
#      run: |
#        GIT_DESCRIBE=$(git describe --always)
#        BRANCH=${GITHUB_REF#refs/heads/}
#        echo GIT_DESCRIBE is $GIT_DESCRIBE, BRANCH is $BRANCH
#        aws s3 cp --no-progress --region eu-west-1 ./target/shaded/$GIT_DESCRIBE.jar s3://r5-builds/$BRANCH-latest.jar
